### ISSUE TITLE
How to connect this to openmaint?

### ISSUE THREAD

**Issue by infeeeee** [astmnk/docker-bimserver#1]
Hello! Thank you for this docker it's working standalone very well.

However I found that OpenMaint expects that bimserver is from the same server. Can you share some working configuration how to connect from OpenMaint docker to this container? As you write about the connection, I guess you got it working. Maybe somethin in `server.xml` or `context.xml` should be changed? Or am I totally wrong? Or with your [docker-openmaint](https://github.com/astmnk/docker-openmaint) it should work? I'm trying to make it work with https://github.com/itmicus/cmdbuild_docker/tree/master/openmaint-2.3-3.4.1-d

Thank you!

**Comment by astmnk** [comment]
Hi @infeeeee, I don't work anymore on this project, but at the time I was able to connect OpenMaint to BIMServer by using the [docker-openmaint](https://github.com/astmnk/docker-openmaint) repository, which combines elements from these two projects [docker-bimserver](https://github.com/astmnk/docker-bimserver) and [openmaint-2.3-3.4.1-d](https://github.com/itmicus/cmdbuild_docker/tree/master/openmaint-2.3-3.4.1-d). However, there was one notable challenge that I recall. It was necessary to ensure that you had BIMserver v1.5.138 installed and that the admin account was activated.

**Comment by infeeeee** [comment]
Thank you!

It seems to me the problem is with openmaint 2.3. With 2.1 everything is working as expected, using your images. So different hosts shouldn't matter, my initial guess were wrong. 

I didn't need your password reset hack, openmaint 2.1 happily accepted the password I gave on installation, it's not an universal bug I guess.

Thank you for your help!
